/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Colegio;

/**
 *
 * @author Admin
 */
public class Colegio extends javax.swing.JFrame {

    /**
     * Creates new form colegio
     */
    public Colegio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmiAgregarAlumno = new javax.swing.JMenuItem();
        jmiBorrarAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmiAgregarMateria = new javax.swing.JMenuItem();
        jmiBorrarMateria = new javax.swing.JMenuItem();
        jmRegistro = new javax.swing.JMenu();
        jmiFormulario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base de Datos del Colegio");

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jmAlumno.setText("Alumno");

        jmiAgregarAlumno.setText("Agregar Alumno");
        jmiAgregarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jmiAgregarAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jmiAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiAgregarAlumno);

        jmiBorrarAlumno.setText("Borrar Alumno");
        jmiBorrarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jmiBorrarAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jmiBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiBorrarAlumno);

        jMenuBar.add(jmAlumno);

        jmMateria.setText("Materia");

        jmiAgregarMateria.setText("Agregar Materia");
        jmiAgregarMateria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jmiAgregarMateria.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jmiAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarMateriaActionPerformed(evt);
            }
        });
        jmMateria.add(jmiAgregarMateria);

        jmiBorrarMateria.setText("Borrar Materia");
        jmiBorrarMateria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jmiBorrarMateria.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jmiBorrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarMateriaActionPerformed(evt);
            }
        });
        jmMateria.add(jmiBorrarMateria);

        jMenuBar.add(jmMateria);

        jmRegistro.setText("Registro");
        jmRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistroActionPerformed(evt);
            }
        });

        jmiFormulario.setText("Formulario");
        jmiFormulario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jmiFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jmiFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioActionPerformed(evt);
            }
        });
        jmRegistro.add(jmiFormulario);

        jMenuBar.add(jmRegistro);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarAlumnoActionPerformed
        FormularioAlumnos fa = new FormularioAlumnos();
        jdpEscritorio.add(fa);
        fa.setVisible(true);
        fa.toFront();
    }//GEN-LAST:event_jmiAgregarAlumnoActionPerformed

    private void jmiAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarMateriaActionPerformed
        FormularioMaterias fm = new FormularioMaterias();
        jdpEscritorio.add(fm);
        fm.setVisible(true);
        fm.toFront();
    }//GEN-LAST:event_jmiAgregarMateriaActionPerformed

    private void jmiBorrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarMateriaActionPerformed
        BorrarMateria bm = new BorrarMateria();
        jdpEscritorio.add(bm);
        bm.setVisible(true);
        bm.toFront();
    }//GEN-LAST:event_jmiBorrarMateriaActionPerformed

    private void jmiBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarAlumnoActionPerformed
        BorrarAlumno ba = new BorrarAlumno();
        jdpEscritorio.add(ba);
        ba.setVisible(true);
        ba.toFront();
    }//GEN-LAST:event_jmiBorrarAlumnoActionPerformed

    private void jmRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistroActionPerformed

    }//GEN-LAST:event_jmRegistroActionPerformed

    private void jmiFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioActionPerformed
        FormularioInscripcion fi = new FormularioInscripcion();
        jdpEscritorio.add(fi);
        fi.setVisible(true);
        fi.toFront();
    }//GEN-LAST:event_jmiFormularioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenu jmRegistro;
    private javax.swing.JMenuItem jmiAgregarAlumno;
    private javax.swing.JMenuItem jmiAgregarMateria;
    private javax.swing.JMenuItem jmiBorrarAlumno;
    private javax.swing.JMenuItem jmiBorrarMateria;
    private javax.swing.JMenuItem jmiFormulario;
    // End of variables declaration//GEN-END:variables
}
