/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Colegio;

import static Colegio.Colegio.alumnoStatic;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class FormularioAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioAlumnos
     */
    
    
    public FormularioAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoFormulario = new javax.swing.JLabel();
        textoLegajo = new javax.swing.JLabel();
        textoApellido = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        cuadoIngresoLeg = new javax.swing.JTextField();
        cuadroIngresoApe = new javax.swing.JTextField();
        cuadroIngresoNom = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonNuevo = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        textoFormulario.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        textoFormulario.setForeground(new java.awt.Color(0, 102, 255));
        textoFormulario.setText("Formulario Alumno");

        textoLegajo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoLegajo.setForeground(new java.awt.Color(0, 102, 255));
        textoLegajo.setText("Legajo:");
        textoLegajo.setEnabled(false);

        textoApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoApellido.setForeground(new java.awt.Color(0, 102, 255));
        textoApellido.setText("Apellido:");
        textoApellido.setEnabled(false);

        textoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(0, 102, 255));
        textoNombre.setText("Nombre:");
        textoNombre.setEnabled(false);

        cuadoIngresoLeg.setEnabled(false);
        cuadoIngresoLeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadoIngresoLegActionPerformed(evt);
            }
        });

        cuadroIngresoApe.setEnabled(false);

        cuadroIngresoNom.setEnabled(false);

        botonGuardar.setText("Guardar");
        botonGuardar.setEnabled(false);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addComponent(textoFormulario)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoLegajo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoApellido, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cuadoIngresoLeg, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cuadroIngresoApe))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(textoNombre)
                        .addGap(18, 18, 18)
                        .addComponent(cuadroIngresoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textoFormulario)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadoIngresoLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoLegajo))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cuadroIngresoApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuadroIngresoNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonGuardar)
                            .addComponent(botonNuevo)
                            .addComponent(botonSalir)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoApellido)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setBounds(0, 0, 406, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void cuadoIngresoLegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadoIngresoLegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadoIngresoLegActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        try{
        int aux = Integer.parseInt(cuadoIngresoLeg.getText());
        Alumno a = new Alumno(aux,cuadroIngresoApe.getText(),cuadroIngresoNom.getText());
        if(a != null){
        alumnoStatic.add(a);
        textoLegajo.setEnabled(false);
        cuadoIngresoLeg.setEnabled(false);
        textoApellido.setEnabled(false);
        cuadroIngresoApe.setEnabled(false);
        textoNombre.setEnabled(false);
        cuadroIngresoNom.setEnabled(false);
        botonGuardar.setEnabled(false);
        botonNuevo.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"No existe alumno a agregar");
        }
        JOptionPane.showMessageDialog(null,"Se ha guardado el alumno: " + a.getApellido() +" "+ a.getNombre());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Los datos ingresados no son los esperados, intentelo de nuevo.");
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        textoLegajo.setEnabled(true);
        cuadoIngresoLeg.setEnabled(true);
        cuadoIngresoLeg.setText("");
        textoApellido.setEnabled(true);
        cuadroIngresoApe.setEnabled(true);
        cuadroIngresoApe.setText("");
        textoNombre.setEnabled(true);
        cuadroIngresoNom.setEnabled(true);
        cuadroIngresoNom.setText("");
        botonGuardar.setEnabled(true);
        botonNuevo.setEnabled(false);
        
        
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField cuadoIngresoLeg;
    private javax.swing.JTextField cuadroIngresoApe;
    private javax.swing.JTextField cuadroIngresoNom;
    private javax.swing.JLabel textoApellido;
    private javax.swing.JLabel textoFormulario;
    private javax.swing.JLabel textoLegajo;
    private javax.swing.JLabel textoNombre;
    // End of variables declaration//GEN-END:variables
}
